import java.io.Serializable;

public class User implements Serializable {

    // generated by ME
    private static final long serialVersionUID = 1L;
    String name;
    transient String password;

    public void sayHello() {
        System.out.println("Hello " + name);
    }
}
